# Generated by Django 6.0 on 2026-04-03 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorSlot', '0002_timeslot'),
        ('appointments', '0002_appointment_patient_name_appointment_patient_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DoctorSlot.timeslot'),
        ),
    ]
