# Generated by Django 5.2.6 on 2026-02-21 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dr_personalInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorpersonalinfo',
            name='photo',
        ),
    ]
