# Generated by Django 6.0 on 2026-04-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dr_personalInfo', '0002_remove_doctorpersonalinfo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpersonalinfo',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='incomplete', max_length=15),
        ),
    ]
