# Generated by Django 6.0 on 2026-04-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dr_personalInfo', '0005_doctorpersonalinfo_rejeted_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpersonalinfo',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='incomplete', max_length=15),
        ),
    ]
