# Generated by Django 5.2.6 on 2026-02-21 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dr_personalInfo', '0002_remove_doctorpersonalinfo_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorHospitalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField()),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('visiting', 'Visiting')], max_length=20)),
                ('consultation_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leave_day', models.CharField(help_text='e.g. Sunday or Monday', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_info', to='Dr_personalInfo.doctorpersonalinfo')),
            ],
        ),
    ]
