# Generated by Django 5.2.6 on 2026-02-21 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dr_personalInfo', '0002_remove_doctorpersonalinfo_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('medical_license', 'Medical License'), ('medical_certificate', 'Medical Certificate'), ('experience_letter', 'Experience Letter'), ('other', 'Other')], max_length=50)),
                ('document_file', models.FileField(upload_to='doctor_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Dr_personalInfo.doctorpersonalinfo')),
            ],
        ),
    ]
